import os

from scenarionet.common_utils import read_dataset_summary, read_scenario

SCENARIONET_PACKAGE_PATH = os.path.dirname(os.path.abspath(__file__))
SCENARIONET_REPO_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCENARIONET_DATASET_PATH = os.path.join(SCENARIONET_REPO_PATH, "dataset")

# use this dir to store junk files generated by testing
TMP_PATH = os.path.join(SCENARIONET_PACKAGE_PATH, "tests", "tmp")
