# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scenarionet/converter/waymo/waymo_protos/compressed_lidar.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

from scenarionet.converter.waymo.waymo_protos import dataset_pb2 as scenarionet_dot_converter_dot_waymo_dot_waymo__protos_dot_dataset__pb2

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n?scenarionet/converter/waymo/waymo_protos/compressed_lidar.proto\x12\x12waymo.open_dataset\x1a\x36scenarionet/converter/waymo/waymo_protos/dataset.proto\"g\n\x14\x43ompressedRangeImage\x12$\n\x1crange_image_delta_compressed\x18\x01 \x01(\x0c\x12)\n!range_image_pose_delta_compressed\x18\x04 \x01(\x0c\"2\n\x08Metadata\x12\r\n\x05shape\x18\x01 \x03(\x05\x12\x17\n\x0fquant_precision\x18\x02 \x03(\x02\"j\n\x10\x44\x65ltaEncodedData\x12\x14\n\x08residual\x18\x01 \x03(\x12\x42\x02\x10\x01\x12\x10\n\x04mask\x18\x02 \x03(\rB\x02\x10\x01\x12.\n\x08metadata\x18\x03 \x01(\x0b\x32\x1c.waymo.open_dataset.Metadata\"\xbf\x01\n\x0f\x43ompressedLaser\x12\x30\n\x04name\x18\x01 \x01(\x0e\x32\".waymo.open_dataset.LaserName.Name\x12<\n\nri_return1\x18\x02 \x01(\x0b\x32(.waymo.open_dataset.CompressedRangeImage\x12<\n\nri_return2\x18\x03 \x01(\x0b\x32(.waymo.open_dataset.CompressedRangeImage\"\xbe\x01\n\x18\x43ompressedFrameLaserData\x12\x33\n\x06lasers\x18\x01 \x03(\x0b\x32#.waymo.open_dataset.CompressedLaser\x12@\n\x12laser_calibrations\x18\x02 \x03(\x0b\x32$.waymo.open_dataset.LaserCalibration\x12+\n\x04pose\x18\x03 \x01(\x0b\x32\x1d.waymo.open_dataset.Transform'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, 'scenarionet.converter.waymo.waymo_protos.compressed_lidar_pb2', _globals
)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals['_DELTAENCODEDDATA'].fields_by_name['residual']._options = None
    _globals['_DELTAENCODEDDATA'].fields_by_name['residual']._serialized_options = b'\020\001'
    _globals['_DELTAENCODEDDATA'].fields_by_name['mask']._options = None
    _globals['_DELTAENCODEDDATA'].fields_by_name['mask']._serialized_options = b'\020\001'
    _globals['_COMPRESSEDRANGEIMAGE']._serialized_start = 143
    _globals['_COMPRESSEDRANGEIMAGE']._serialized_end = 246
    _globals['_METADATA']._serialized_start = 248
    _globals['_METADATA']._serialized_end = 298
    _globals['_DELTAENCODEDDATA']._serialized_start = 300
    _globals['_DELTAENCODEDDATA']._serialized_end = 406
    _globals['_COMPRESSEDLASER']._serialized_start = 409
    _globals['_COMPRESSEDLASER']._serialized_end = 600
    _globals['_COMPRESSEDFRAMELASERDATA']._serialized_start = 603
    _globals['_COMPRESSEDFRAMELASERDATA']._serialized_end = 793
# @@protoc_insertion_point(module_scope)
