# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  repository_dispatch:
    types: [metadrive-update]
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Check code style
        run: |
          pip install "yapf==0.30.0"
          bash format.sh --test

  test_functionality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install tensorflow==2.11.0
          pip install protobuf==3.20
          pip install cython
          pip install numpy
          pip install -e .
          pip install pytest
          pip install pytest-cov
          pip install ray
          
          git clone https://github.com/metadriverse/metadrive.git
          cd metadrive
          pip install -e .
          cd ../
          
          cd scenarionet/
          pytest --cov=./ --cov-config=.coveragerc --cov-report=xml -sv tests


  test_ipynb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Blackbox tests
        run: |
          pip install cython
          pip install numpy
          pip install -e .
          pip install pytest
          pip install pytest-cov
          pip install ray
          git clone https://github.com/metadriverse/metadrive.git
          cd metadrive
          pip install -e .
          cd ../
          pip install nbmake pytest-xdist
          pytest --nbmake -n=auto ./tutorial/